// <auto-generated />
using System.Collections.Generic;
using ComplexTypeBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplexTypeBug.Migrations
{
    [DbContext(typeof(ComplexTypeBugDbContext))]
    [Migration("20251015173049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplexTypeBug.Models.TableWithComplexType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("Enum")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "ComplexTypeBug.Models.TableWithComplexType.Token0#Token", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "ComplexTypeBug.Models.TableWithComplexType.Token1#Token", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Name", "Value");

                    b.ToTable("TableWithComplexType");
                });

            modelBuilder.Entity("ComplexTypeBug.Models.TableWithSameComplexType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "ComplexTypeBug.Models.TableWithSameComplexType.Token0#Token", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "ComplexTypeBug.Models.TableWithSameComplexType.Token1#Token", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Name", "Value");

                    b.ToTable("TableWithSameComplexType");
                });
#pragma warning restore 612, 618
        }
    }
}
